exp_name: LPVFI
seed: 2023
epochs: 300
switch_epochs: 200
distributed: false
lr: 2e-4
lr_min: 1e-5
weight_decay: 0.0
resume_state: null
save_dir: work_dir
eval_interval: 1

network:
  name: networks.LPVFI-AMT-S.Model
  params:
    corr_radius: 3
    corr_lvls: 4
    num_flows: 3

data:
  train:
    name: datasets.vimeo_datasets.Vimeo90K_Train_Dataset
    params:
      dataset_dir: /root/autodl-tmp/IFR/data/Vimeo90k
  val:
    name: datasets.vimeo_datasets.Vimeo90K_Test_Dataset
    params:
      dataset_dir: /root/autodl-tmp/IFR/data/Vimeo90k
  train_loader:
    batch_size: 24
    num_workers: 8
  val_loader:
    batch_size: 24
    num_workers: 8

logger:
  use_wandb: false
  resume_id: null

losses:
  - {
    name: losses.loss.CharbonnierLoss,
    nickname: l_rec,
    params: {
      loss_weight: 1.0,
      keys: [imgt_pred, imgt]
    }
  }
  - {
    name: losses.loss.TernaryLoss,
    nickname: l_ter,
    params: {
      loss_weight: 1.0,
      keys: [imgt_pred, imgt]
    }
  }
  - {
    name: losses.loss.MultipleFlowLoss,
    nickname: l_flo,
    params: {
      loss_weight: 0.002,
      keys: [flow0_pred, flow1_pred, flow]
    }
  }

